pr:
  - master

variables:
  BuildContainer: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview4
  VmImage: ubuntu-16.04

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: library
        displayName: Library
        container: $(BuildContainer)
        pool:
          vmImage: '$(VmImage)'
        workspace:
          clean: all
        timeoutInMinutes: 60
        cancelTimeoutInMinutes: 60
        variables:
          ProjectsTest: src/MvvmBlazor/*.csproj
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: '$(ProjectsTest)'
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: publish
              arguments: '-c Release -o out'
              projects: '$(ProjectsTest)'
          - task: CopyFiles@2
            inputs:
              contents: 'out\*.nupkg'
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: $(Build.ArtifactStagingDirectory)
              artifactName: NuGet Package
      - job: samples
        displayName: Samples
        container: $(BuildContainer)
        pool:
          vmImage: '$(VmImage)'
        workspace:
          clean: all
        timeoutInMinutes: 60
        cancelTimeoutInMinutes: 60
        variables:
          Projects: samples/*/*.csproj
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: '$(Projects)'
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              arguments: '-c Release'
              projects: '$(Projects)'
  - stage: test
    displayName: Test
    jobs:
      - job: unit_test
        displayName: Unit-Tests
        container: $(BuildContainer)
        pool:
          vmImage: '$(VmImage)'
        workspace:
          clean: all
        timeoutInMinutes: 60
        cancelTimeoutInMinutes: 60
        variables:
          Projects: src/MvvmBlazor.Tests/*.csproj
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: '$(Projects)'
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: test
              arguments: '-c Release --collect "Code coverage"'
              projects: '$(Projects)'