name: $(Build.BuildNumber)
pr:
  - master

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: library
        displayName: Library
        container: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview4
        pool:
          vmImage: 'ubuntu-16.04'
        workspace:
          clean: all
        timeoutInMinutes: 60
        cancelTimeoutInMinutes: 60
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: 'src/*/*.csproj'
      - job: samples
        displayName: Samples
        container: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview4
        pool:
          vmImage: 'ubuntu-16.04'
        workspace:
          clean: all
        timeoutInMinutes: 60
        cancelTimeoutInMinutes: 60
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: 'samples/*/*.csproj'