pr:
  - master

variables: 
  PackageVersion: '1.0.0'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: library
        displayName: Library
        container: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview4
        pool:
          vmImage: ubuntu-16.04
        workspace:
          clean: all
        timeoutInMinutes: 60
        cancelTimeoutInMinutes: 60
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: 'src'
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              arguments: '-c Release'
              projects: 'src'
          - task: DotNetCoreCLI@2
            displayName: Pack
            inputs:
              command: pack
              arguments: '-c Release -o out /p:Version=$(PackageVersion)'
              projects: 'src/MvvmBlazor/MvvmBlazor.csproj'
          - task: CopyFiles@2
            inputs:
              contents: 'out\*.nupkg'
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: $(Build.ArtifactStagingDirectory)
              artifactName: NuGet Package
  - stage: test
    displayName: Test
    jobs:
      - job: unit_test
        displayName: Unit-Tests
        container: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview4
        pool:
          vmImage: ubuntu-16.04
        workspace:
          clean: all
        timeoutInMinutes: 60
        cancelTimeoutInMinutes: 60
        variables:
          Projects: 'src/MvvmBlazor.Tests/*.csproj'
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: $(Projects)
          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: test
              arguments: '-c Release --collect "Code coverage"'
              projects: $(Projects)